Index: expokit-1.0/fortran/Makefile
===================================================================
--- expokit-1.0.orig/fortran/Makefile	2009-09-14 10:57:45.000000000 +0200
+++ expokit-1.0/fortran/Makefile	2009-09-14 11:01:00.000000000 +0200
@@ -1,52 +1,72 @@
-FC	= f77
+FC	= gfortran
 FFLAGS	= -O3
 
-# Among the 3 possibilities below, uncomment the appropriate
-# case for your environment and comment the others.
-
-# case 1: works when LAPACK and BLAS are installed.
-#OBJLIBS =
-#LIBS    = -llapack -lblas
-
-# case 2: works when LAPACK is not installed but BLAS is.
-#LIBS    = -lblas
-#OBJLIBS = lapack.o
-
-# case 3: works when neither LAPACK nor BLAS are installed.
-OBJLIBS = blas.o lapack.o
-LIBS	=
+LIBS    = -llapack -lblas
 
 #############
 #############
 
 EXPOKIT   = expokit.o
-#EXPOKIT   = dgpadm.o dspadm.o zgpadm.o zhpadm.o                    \
-#            dgchbv.o dschbv.o zgchbv.o          dnchbv.o znchbv.o  \
-#            dgexpv.o dsexpv.o zgexpv.o zhexpv.o                    \
-#            dgphiv.o dsphiv.o zgphiv.o zhphiv.o 
-
 MATAID    = mataid.o
-#MATAID    = dgmatv.o zgmatv.o \
-#            dgcnvr.o zgcnvr.o loadhb.o
 
-OBJS      = clock.o $(EXPOKIT) $(MATAID) $(OBJLIBS)
+OBJS      = clock.o params.o $(EXPOKIT) $(MATAID) $(OBJLIBS)
+
+all: lib
+
+lib: libexpokit.a libexpokit.so.1.0.0
 
-sample_g: $(OBJS) sample_g.o
-	$(FC) -o sample_g sample_g.o $(OBJS) $(LIBS)
+libexpokit.a:	$(OBJS)
+	ar -crv $@ clock.o params.o $(EXPOKIT) $(MATAID) 
 
-sample_b: $(OBJS) sample_b.o
-	$(FC) -o sample_b sample_b.o $(OBJS) $(LIBS)
+libexpokit.so.1.0.0:	$(OBJS)
+	$(FC) -shared -Wl,-soname=libexpokit.so.1 -o $@ clock.o params.o $(EXPOKIT) $(MATAID) $(LIBS) 
 
-sample_z: $(OBJS) sample_z.o
-	$(FC) -o sample_z sample_z.o $(OBJS) $(LIBS)
+sample_g: libexpokit.a sample_g.o
+	$(FC) -o sample_g sample_g.o -L. -lexpokit $(LIBS)
 
-sample_m: $(OBJS) sample_m.o
-	$(FC) -o sample_m sample_m.o $(OBJS) $(LIBS)
+sample_b: libexpokit.a sample_b.o
+	$(FC) -o sample_b sample_b.o -L. -lexpokit $(LIBS)
+
+sample_z: libexpokit.a sample_z.o
+	$(FC) -o sample_z sample_z.o -L. -lexpokit $(LIBS)
+
+sample_m: libexpokit.a sample_m.o
+	$(FC) -o sample_m sample_m.o -L. -lexpokit $(LIBS)
  
-sample_d: $(OBJS) sample_d.o
-	$(FC) -o sample_d sample_d.o $(OBJS) $(LIBS)
+sample_d: libexpokit.a sample_d.o
+	$(FC) -o sample_d sample_d.o -L. -lexpokit $(LIBS)
+
+sample_p: libexpokit.a sample_p.o
+	$(FC) -o sample_p sample_p.o -L. -lexpokit $(LIBS)
+
+check:	tests
 
-sample_p: $(OBJS) sample_p.o
-	$(FC) -o sample_p sample_p.o $(OBJS) $(LIBS)
 
+tests:	
+	make sample_g && ./sample_g
+	make sample_b && ./sample_b
+	make sample_z && ./sample_z
+	make sample_m && ./sample_m
+	make sample_d && ./sample_d
+	make sample_p && ./sample_p
+
+install:
+	mkdir -p $(DESTDIR)/usr/lib
+	mkdir -p $(DESTDIR)/usr/share/libexpokit/data
+	mkdir -p $(DESTDIR)/usr/share/libexpokit/matlab
+	mkdir -p $(DESTDIR)/usr/share/libexpokit/examples
+	install -m 644 libexpokit.a $(DESTDIR)/usr/lib
+	install -m 644 libexpokit.so.1.0.0 $(DESTDIR)/usr/lib
+	cd $(DESTDIR)/usr/lib && ln -snf libexpokit.so.1.0.0 libexpokit.so.1
+	cd $(DESTDIR)/usr/lib && ln -snf libexpokit.so.1.0.0 libexpokit.so 
+	install -m 644 sample_*.f $(DESTDIR)/usr/share/libexpokit/examples
+	install -m 644 ../data/* $(DESTDIR)/usr/share/libexpokit/data
+	install -m 644 ../matlab/*.m $(DESTDIR)/usr/share/libexpokit/matlab
+	
+clean:
+	rm -f *.o sample_[gbzmdp]
+	
+distclean:
+	rm -f libexpokit.*
+	
 .f.o:;  $(FC) $(FFLAGS) -c $<
